version: "3.9"
services:

  # Redis
  redis:
    image: redis:alpine
    container_name: meeting_website_redis
    ports:
      - 6381:6379

  # Database Postgres
  db:
    image: postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=meeting_website
    ports:
      - ${POSTGRES_PORT:-5441}:5432
    container_name: meeting_website_postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d meeting_website" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  # Django App
  web:
    build: .
    volumes:
      - .:/django
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - 8011:8011
    links:
      - db
    image: app:django
    container_name: meeting_website_web
    command: /wait-for-it.sh db:5432 -- python3 manage.py runserver 0.0.0.0:8011
    depends_on:
      - db
    env_file:
      - ./meeting_website/.env

  # Celery
  celery:
    restart: always
    build:
      context: .
    command: celery -A meeting_website worker -l INFO
    volumes:
      - .:/django
    container_name: meeting_website_celery
    links:
      - redis
    depends_on:
      - db
      - redis
      - web
